---
# install_and_configure_etcd/tasks/main.yml

- name: 'Load variables'
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution | replace(' ', '_') }}{{ ansible_distribution_major_version }}.yml"
    - "vars_{{ ansible_distribution | replace(' ', '_') }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

- name: 'Run pre-flight checks'
  ansible.builtin.include_tasks: preflight_checks.yml

- name: 'Assemble etcd_initial_cluster from user-supplied group of servers'
  ansible.builtin.include_tasks: prepare_server_list_for_etcd_initial_cluster.yml
  when:
    - 'etcd_initial_cluster is undefined'
    - 'etcd_servers_group is defined'

- name: 'Create systemd drop-in if v2 needs to be enabled'
  ansible.builtin.include_tasks: enable_api_v2.yml
  when:
    - 'enable_api_v2 | bool'

- name: 'Install the etcd package'
  ansible.builtin.package:
    name: "{{ package_name }}"
    state: 'present'

- name: 'Install the etcdctl package'
  ansible.builtin.package:
    name: "{{ etcdctl_package_name }}"
    state: 'present'

- name: "Create {{ sysconfig_file_path }}"
  ansible.builtin.template:
    src: 'etc_sysconfig_etcd.j2'
    dest: "{{ sysconfig_file_path }}"
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
    - 'Restart the etcd service'

- name: 'Start and enable the etcd service'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: 'started'
    enabled: 'true'
