---
# install_and_configure_etcd/tasks/prepare_server_list_for_etcd_initial_cluster.yml

- name: 'Create empty variable etcd_initial_cluster'
  ansible.builtin.set_fact:
    etcd_initial_cluster: ''

- name: 'Create string with hostname and IP address for each hosts and add to variable etcd_initial_cluster'
  ansible.builtin.set_fact:
    etcd_initial_cluster:
      "{{ etcd_initial_cluster  + hostvars[item]['inventory_hostname'] + '=http://' + hostvars[item]['ansible_default_ipv4']['address'] + ':2380,' }}"
  with_items: "{{ groups[etcd_servers_group] }}"

- name: 'Remove trailing comma in variable etcd_initial_cluster'
  ansible.builtin.set_fact:
    etcd_initial_cluster: "{{ etcd_initial_cluster | regex_replace(',$', '') }}"

- name: debug
  debug:
    var: etcd_initial_cluster

- name: 'Set etcd_name to inventory hostname'
  ansible.builtin.set_fact:
    etcd_name: "{{ inventory_hostname }}"
