---
# install_and_configure_etcd/handlers/main.yml

- name: 'Trigger systemctl daemon-reload'
  ansible.builtin.systemd:
    daemon_reload: 'yes'

- name: 'Restart the etcd service'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: 'restarted'
